# GENERATED by scripts/export-public.sh — do not edit.
# Derived from nix/public-allowlist.nix in the source repository.
{
  agents        = { path = ../agents; subdir = "skills"; filter.maxDepth = 1; };
}
